# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Configuration memory and cpus
  config.vm.provider "virtualbox" do |v|
    v.memory = 10240
    v.cpus = 4
    v.name = "docker"
  end

  # CentOS 7 with VBox Additions
  config.vm.box = "centos/7"
  config.vbguest.auto_update = true

  # Shared dirs
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "/Users/skumpf/git/ycloud", "/ycloud"

  # Run the common bootstrap script
  config.vm.provision :shell, path: "tools/bootstrap_common.sh"

end
